### PR TITLE
support the newer libre 2 plus european sensors with 15 days runtime,…

### PR DESCRIPTION
**Pull request by dabear**
… for reference: https://github.com/JohanDegraeve/xdripswift/commit/d2462dc2b95d17e98a0a1be7682d74ad78e2573d

### CODE REVIEW

**Comment by dabear** [comment]
Needs testing by others, since I don't have access to these newer "libre 2 plus" sensors

**Comment by elpececillo** [comment]
I am new to this, but with the help of an xcode programmer I was able to make the necessary changes as indicated on line 113. 
Loop did not recognize the free 2 plus from Latin America. I am in Chile.
I also tried with “2B”, without success from Guido's post in Zulip that was deleted.

image

**Comment by dabear** [comment]
Only European models are supported by this patch

**Comment by gui-dos** [comment]
@elpececillo 
> Guido's post in Zulip that was deleted.

I am also here on GitHub (https://github.com/gui-dos/DiaBLE/blob/4c72730c4b7c50e8554bbc651e81d094466a5069/DiaBLE/Libre.swift#L34-L37) and more than willing to discuss openly about the intenals of the Libre sensors! ;-)

The layout of the sensor memory ("FRAM") is the same for all the Libre 1 and Libre 2 models, as well as the amount and kind of data sent every minute via Bluetooth (three packets of 20 + 18 + 8 bytes encoding for 7 sparse 1-minute "trend" values and the latest three "historical" values).

While in the European models the keys to decrypt the NFC and BLE data are fixed and the algorithms have been reversed engineered successfully by the FreeAPS team (I was the first one to publish them since I was able to dump them from the sensor memory B-), the newer "Gen2" models follow enhanced multi-stage challenge-repsonse protocols and the ephemeral keys are generated at each new "secured" connection (https://github.com/gui-dos/DiaBLE/blob/main/DiaBLE/Gen2.swift).

AFAIK not even the Android DiaBox and Juggluco developers succeeded in revere engineering the obfuscated C++ native methods `P1()` and `P2()` and they have to redistribute and inject into the `libdataprocessing.so` binary, hence the DMCA takedown requests by the Vendor.

**Comment by dabear** [comment]
Confirmed this works with libre 2 plus sensors

C774EA16-A4BC-4510-827E-14805E981A4B_1_201_a

**Pull request merged**
